// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hatsoujerbccpczcbgnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhdHNvdWplcmJjY3BjemNiZ252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDc3MzgsImV4cCI6MjA2Nzg4MzczOH0.n4EWhxxpGMcrMPSlNgh-sUcWvz-_bZiLGW3roGvH9io";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});